SHELL := /bin/bash

DOCKER_COMPOSE ?= docker compose

SERVICE_COMPOSE := deployments/service/docker-compose.yml
BTC_COMPOSE := deployments/local-chains/docker-compose.btc.yml
ETH_COMPOSE := deployments/local-chains/docker-compose.eth.yml

SERVICE_PROJECT := chaintx-local-service
BTC_PROJECT := chaintx-local-btc
ETH_PROJECT := chaintx-local-eth

ARTIFACT_DIR := deployments/local-chains/artifacts
SCRIPT_DIR := scripts/local-chains
BTC_ARTIFACT := $(ARTIFACT_DIR)/btc.json
ETH_ARTIFACT := $(ARTIFACT_DIR)/eth.json
SMOKE_LOCAL_ARTIFACT := $(ARTIFACT_DIR)/smoke-local.json
SMOKE_ALL_ARTIFACT := $(ARTIFACT_DIR)/smoke-local-all.json
SERVICE_RECEIVE_PROOF_ARTIFACT := $(ARTIFACT_DIR)/service-receive-local-all.json

BTC_RPC_USER ?= chaintx
BTC_RPC_PASSWORD ?= chaintx
BTC_RPC_URL ?= http://127.0.0.1:18443
ETH_RPC_URL ?= http://127.0.0.1:8545

SERVICE_KS_BTC_REGTEST ?= tpubDC2pzLGKv5DoHtRoYjJsbgESSzFqc3mtPzahMMqhH89bqqHot28MFUHkUECJrBGFb2KPQZUrApq4Ti6Y69S2K3snrsT8E5Zjt1GqTMj7xn5
SERVICE_KS_BTC_TESTNET ?= vpub5Xzfrm6ouSBPKVriRpkXyai4mvsHjRHq28wxS1znBCdwzLzeJUx8ruJeBnCMKs1AyqYsJ2mriQHuzxNoFtkkq94J4bJyNjGXkbZ8vCYwUy3
SERVICE_KS_ETH_SEPOLIA ?= xpub6BfCU6SeCoGM26Ex6YKnPku57sABcfGprMzPzonYwDPi6Yd6ooHG72cvEC7XKgK1o7nUnyxydj11mXbvhHanRcRVoGhpYYuWJ3gRhPCmQKj
SERVICE_KS_ETH_LOCAL ?= $(SERVICE_KS_ETH_SEPOLIA)
SERVICE_KS_BTC_REGTEST_INDEX0_ADDRESS ?= bcrt1q7xfwy8t0z9xar2klctmdgm96kxvg9k8jn30qfg
SERVICE_KS_BTC_TESTNET_INDEX0_ADDRESS ?= tb1q7xfwy8t0z9xar2klctmdgm96kxvg9k8j3ckd7p
SERVICE_KS_ETH_SEPOLIA_INDEX0_ADDRESS ?= 0x61ed32e69db70c5abab0522d80e8f5db215965de
SERVICE_KS_ETH_LOCAL_INDEX0_ADDRESS ?= $(SERVICE_KS_ETH_SEPOLIA_INDEX0_ADDRESS)
SERVICE_KEYSET_HASH_HMAC_SECRET ?= local-devtest-hmac-secret-change-me
SERVICE_KEYSET_HASH_HMAC_PREVIOUS_SECRETS_JSON ?=
SERVICE_APP_RECONCILER_ENABLED ?= false
SERVICE_APP_RECONCILER_WORKER_ID ?=
SERVICE_RECONCILER_ENABLED ?= false
SERVICE_RECONCILER_REPLICAS ?= 1
SERVICE_RECONCILER_POLL_INTERVAL_SECONDS ?= 15
SERVICE_RECONCILER_BATCH_SIZE ?= 100
SERVICE_RECONCILER_LEASE_SECONDS ?= 30
SERVICE_RECONCILER_WORKER_ID ?=
SERVICE_RECONCILER_DETECTED_THRESHOLD_BPS ?= 10000
SERVICE_RECONCILER_CONFIRMED_THRESHOLD_BPS ?= 10000
SERVICE_RECONCILER_BTC_MIN_CONFIRMATIONS ?= 1
SERVICE_RECONCILER_EVM_MIN_CONFIRMATIONS ?= 1
SERVICE_BTC_ESPLORA_BASE_URL ?=
SERVICE_EVM_RPC_URLS_JSON ?= {}

SERVICE_DC := $(DOCKER_COMPOSE) -f $(SERVICE_COMPOSE) --project-name $(SERVICE_PROJECT)
BTC_DC := $(DOCKER_COMPOSE) -f $(BTC_COMPOSE) --project-name $(BTC_PROJECT)
ETH_DC := $(DOCKER_COMPOSE) -f $(ETH_COMPOSE) --project-name $(ETH_PROJECT)
BTC_DC_WITH_EXPLORER := COMPOSE_PROFILES=btc-explorer $(BTC_DC)
ETH_DC_WITH_EXPLORER := COMPOSE_PROFILES=eth-explorer $(ETH_DC)
BTC_BOOTSTRAP_CMD := \
	LOCAL_CHAIN_ARTIFACT_DIR="$(ARTIFACT_DIR)" \
	LOCAL_BTC_PROJECT="$(BTC_PROJECT)" \
	BTC_COMPOSE_FILE="$(BTC_COMPOSE)" \
	BTC_RPC_USER="$(BTC_RPC_USER)" \
	BTC_RPC_PASSWORD="$(BTC_RPC_PASSWORD)" \
	BTC_RPC_URL="$(BTC_RPC_URL)" \
	$(SCRIPT_DIR)/btc_bootstrap.sh
ETH_EXPORT_CMD := \
	LOCAL_CHAIN_ARTIFACT_DIR="$(ARTIFACT_DIR)" \
	LOCAL_ETH_PROJECT="$(ETH_PROJECT)" \
	ETH_COMPOSE_FILE="$(ETH_COMPOSE)" \
	ETH_RPC_URL="$(ETH_RPC_URL)" \
	ETH_EXPECTED_CHAIN_ID="31337" \
	SERVICE_KS_ETH_SEPOLIA="$(SERVICE_KS_ETH_SEPOLIA)" \
	$(SCRIPT_DIR)/eth_export_artifacts.sh
ETH_USDT_DEPLOY_CMD := ETH_RPC_URL="http://eth-node:8545" ETH_EXPECTED_CHAIN_ID="31337" $(ETH_DC) run --rm usdt-deployer

# Add new service env mappings here; service-up recipe should stay unchanged.
SERVICE_KEYSETS_JSON_SOURCE_ENV := \
	BTC_ARTIFACT_FILE="$(BTC_ARTIFACT)" \
	ETH_ARTIFACT_FILE="$(ETH_ARTIFACT)" \
	SERVICE_KS_BTC_REGTEST="$(SERVICE_KS_BTC_REGTEST)" \
	SERVICE_KS_BTC_TESTNET="$(SERVICE_KS_BTC_TESTNET)" \
	SERVICE_KS_ETH_SEPOLIA="$(SERVICE_KS_ETH_SEPOLIA)" \
	SERVICE_KS_ETH_LOCAL="$(SERVICE_KS_ETH_LOCAL)" \
	SERVICE_KS_BTC_REGTEST_INDEX0_ADDRESS="$(SERVICE_KS_BTC_REGTEST_INDEX0_ADDRESS)" \
	SERVICE_KS_BTC_TESTNET_INDEX0_ADDRESS="$(SERVICE_KS_BTC_TESTNET_INDEX0_ADDRESS)" \
	SERVICE_KS_ETH_SEPOLIA_INDEX0_ADDRESS="$(SERVICE_KS_ETH_SEPOLIA_INDEX0_ADDRESS)" \
	SERVICE_KS_ETH_LOCAL_INDEX0_ADDRESS="$(SERVICE_KS_ETH_LOCAL_INDEX0_ADDRESS)"
SERVICE_VERIFY_KEYSETS_ENV := \
	PAYMENT_REQUEST_DEVTEST_KEYSETS_JSON="$$keysets_json"
SERVICE_COMPOSE_UP_ENV := \
	PAYMENT_REQUEST_DEVTEST_KEYSETS_JSON="$$keysets_json" \
	PAYMENT_REQUEST_KEYSET_HASH_HMAC_SECRET="$(SERVICE_KEYSET_HASH_HMAC_SECRET)" \
	PAYMENT_REQUEST_KEYSET_HASH_HMAC_PREVIOUS_SECRETS_JSON='$(SERVICE_KEYSET_HASH_HMAC_PREVIOUS_SECRETS_JSON)' \
	PAYMENT_REQUEST_APP_RECONCILER_ENABLED="$(SERVICE_APP_RECONCILER_ENABLED)" \
	PAYMENT_REQUEST_APP_RECONCILER_WORKER_ID="$(SERVICE_APP_RECONCILER_WORKER_ID)" \
	PAYMENT_REQUEST_RECONCILER_ENABLED="$(SERVICE_RECONCILER_ENABLED)" \
	PAYMENT_REQUEST_RECONCILER_POLL_INTERVAL_SECONDS="$(SERVICE_RECONCILER_POLL_INTERVAL_SECONDS)" \
	PAYMENT_REQUEST_RECONCILER_BATCH_SIZE="$(SERVICE_RECONCILER_BATCH_SIZE)" \
	PAYMENT_REQUEST_RECONCILER_LEASE_SECONDS="$(SERVICE_RECONCILER_LEASE_SECONDS)" \
	PAYMENT_REQUEST_RECONCILER_WORKER_ID="$(SERVICE_RECONCILER_WORKER_ID)" \
	PAYMENT_REQUEST_RECONCILER_DETECTED_THRESHOLD_BPS="$(SERVICE_RECONCILER_DETECTED_THRESHOLD_BPS)" \
	PAYMENT_REQUEST_RECONCILER_CONFIRMED_THRESHOLD_BPS="$(SERVICE_RECONCILER_CONFIRMED_THRESHOLD_BPS)" \
	PAYMENT_REQUEST_RECONCILER_BTC_MIN_CONFIRMATIONS="$(SERVICE_RECONCILER_BTC_MIN_CONFIRMATIONS)" \
	PAYMENT_REQUEST_RECONCILER_EVM_MIN_CONFIRMATIONS="$(SERVICE_RECONCILER_EVM_MIN_CONFIRMATIONS)" \
	PAYMENT_REQUEST_BTC_ESPLORA_BASE_URL="$(SERVICE_BTC_ESPLORA_BASE_URL)" \
	PAYMENT_REQUEST_EVM_RPC_URLS_JSON='$(SERVICE_EVM_RPC_URLS_JSON)'
SERVICE_SYNC_CATALOG_ENV := \
	PAYMENT_REQUEST_DEVTEST_KEYSETS_JSON="$$keysets_json" \
	PAYMENT_REQUEST_KEYSET_HASH_HMAC_SECRET="$(SERVICE_KEYSET_HASH_HMAC_SECRET)" \
	PAYMENT_REQUEST_KEYSET_HASH_HMAC_PREVIOUS_SECRETS_JSON='$(SERVICE_KEYSET_HASH_HMAC_PREVIOUS_SECRETS_JSON)' \
	SERVICE_COMPOSE_FILE="$(SERVICE_COMPOSE)" \
	LOCAL_SERVICE_PROJECT="$(SERVICE_PROJECT)" \
	ETH_ARTIFACT_FILE="$(ETH_ARTIFACT)"
LOCAL_RECEIVE_TEST_ENV := \
	LOCAL_CHAIN_ARTIFACT_DIR="$(ARTIFACT_DIR)" \
	LOCAL_BTC_PROJECT="$(BTC_PROJECT)" \
	LOCAL_ETH_PROJECT="$(ETH_PROJECT)" \
	LOCAL_SERVICE_PROJECT="$(SERVICE_PROJECT)" \
	BTC_COMPOSE_FILE="$(BTC_COMPOSE)" \
	ETH_COMPOSE_FILE="$(ETH_COMPOSE)" \
	SERVICE_COMPOSE_FILE="$(SERVICE_COMPOSE)" \
	BTC_RPC_USER="$(BTC_RPC_USER)" \
	BTC_RPC_PASSWORD="$(BTC_RPC_PASSWORD)" \
	ETH_RPC_URL="$(ETH_RPC_URL)" \
	ETH_EXPECTED_CHAIN_ID="31337" \
	SERVICE_RECEIVE_PROOF_FILE="$(SERVICE_RECEIVE_PROOF_ARTIFACT)"

.PHONY: \
	service-up service-down \
	chain-up-btc chain-up-btc-no-explorer chain-down-btc \
	chain-up-eth chain-up-eth-no-explorer chain-down-eth \
	chain-up-all chain-up-all-no-explorer chain-down-all \
	local-up local-up-no-explorer local-up-all local-up-all-no-explorer local-down \
	local-receive-test local-receive-proof

service-up:
	@set -eu; \
	keysets_json="$$( \
		env \
			$(SERVICE_KEYSETS_JSON_SOURCE_ENV) \
			$(SCRIPT_DIR)/service_keysets_json.sh \
	)"; \
	env \
		$(SERVICE_VERIFY_KEYSETS_ENV) \
		$(SCRIPT_DIR)/service_verify_keysets.sh; \
	compose_profiles=""; \
	scale_args=""; \
	services="postgres app"; \
	if [ "$(SERVICE_RECONCILER_ENABLED)" = "true" ]; then \
		compose_profiles="reconciler"; \
		scale_args="--scale reconciler=$(SERVICE_RECONCILER_REPLICAS)"; \
		services="$$services reconciler"; \
	fi; \
	env \
		COMPOSE_PROFILES="$$compose_profiles" \
		$(SERVICE_COMPOSE_UP_ENV) \
		$(SERVICE_DC) up -d --build $$scale_args $$services; \
	env \
		$(SERVICE_SYNC_CATALOG_ENV) \
		$(SCRIPT_DIR)/service_sync_catalog.sh

service-down:
	COMPOSE_PROFILES=reconciler $(SERVICE_DC) stop

chain-up-btc: BTC_UP_CMD = $(BTC_DC_WITH_EXPLORER) up -d
chain-up-btc-no-explorer: BTC_UP_CMD = $(BTC_DC) up -d

chain-up-btc chain-up-btc-no-explorer:
	$(BTC_UP_CMD)
	$(BTC_BOOTSTRAP_CMD)

chain-down-btc:
	$(BTC_DC) stop btc-explorer btc-node
	rm -f $(BTC_ARTIFACT) $(SMOKE_LOCAL_ARTIFACT) $(SMOKE_ALL_ARTIFACT)

chain-up-eth: ETH_UP_CMD = $(ETH_DC_WITH_EXPLORER) up -d
chain-up-eth-no-explorer: ETH_UP_CMD = $(ETH_DC) up -d

chain-up-eth chain-up-eth-no-explorer:
	$(ETH_UP_CMD)
	$(ETH_EXPORT_CMD)
	$(ETH_USDT_DEPLOY_CMD)

chain-down-eth:
	$(ETH_DC) stop eth-explorer-frontend eth-explorer eth-explorer-redis eth-explorer-db eth-node
	rm -f $(ETH_ARTIFACT) $(ARTIFACT_DIR)/usdt.json $(SMOKE_ALL_ARTIFACT)

chain-up-all: chain-up-btc chain-up-eth

chain-up-all-no-explorer: chain-up-btc-no-explorer chain-up-eth-no-explorer

chain-down-all: chain-down-eth chain-down-btc

local-up: chain-up-btc service-up

local-up-no-explorer: chain-up-btc-no-explorer service-up

local-up-all: chain-up-all service-up

local-up-all-no-explorer: chain-up-all-no-explorer service-up

local-down: service-down chain-down-all

local-receive-test:
	env \
		$(LOCAL_RECEIVE_TEST_ENV) \
		$(SCRIPT_DIR)/smoke_service_receive_all.sh

local-receive-proof: local-up-all local-receive-test
